imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id: session.handler.mongo
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        contact_email: %contact_email%
        collection_faq: %collection_faq%
        collection_blog: %collection_blog%
        account_exemples: %account_exemples%
        account_try: %account_try%
        locales:
            - [fr, Français]
            - [en, English]

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver:      mongodb
    firewall_name:  main
    user_class:     Datatheke\Bundle\CoreBundle\Document\User

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    serializer:
        serialize_null: true

fos_oauth_server:
    db_driver:      mongodb
    client_class:        Datatheke\Bundle\ApiBundle\Document\Client
    access_token_class:  Datatheke\Bundle\ApiBundle\Document\AccessToken
    refresh_token_class: Datatheke\Bundle\ApiBundle\Document\RefreshToken
    auth_code_class:     Datatheke\Bundle\ApiBundle\Document\AuthCode
    service:
        user_provider: fos_user.user_manager

doctrine_mongodb:
    connections:
        default:
            server: %mongodb_server%
            options:
                connect: true
    default_database: %mongodb_database%
    document_managers:
        default:
            auto_mapping: true
    auto_generate_proxy_classes:    true
    auto_generate_hydrator_classes: true

datatheke_pager:
    datagrid_theme:       DatathekePagerBundle:DataGrid:bootstrap3.html.twig

# MongodDB Session
services:
    session.handler.mongo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        arguments: [@mongo, %mongo.session.options%]

    mongo.connection:
        class: MongoDoctrine\MongoDB\Connection
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getConnection
        calls:
           - [initialize, []]
    mongo:
        class: Mongo
        factory_service: mongo.connection
        factory_method: getMongo

parameters:
    mongo.session.options:
        database: %mongodb_database%
        collection: Session