parameters:
    datatheke.handler.authentication.class: Datatheke\Bundle\FrontendBundle\Security\AuthenticationSuccessHandler

services:
    datatheke.handler.authentication:
        class: %datatheke.handler.authentication.class%
        arguments: [@router]
